version: '3.9'

services:
  db:
    image: mysql:8.0.21
    container_name: mysql_container
    ports:
      - 3002:3306
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=123456
    restart: 'always'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    cap_add:
      - SYS_NICE
    
  backend:
    container_name: backend_container
    build: ./back-end
    ports:
      - 3001:3001
    working_dir: /app-backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_USER=root
      - DB_PASSWORD=123456
      - DB_HOST=db
      - DB_PORT=3306
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3001"]
      timeout: 10s
      retries: 5
  
  frontend:
    container_name: frontend_container
    build: ./front-end
    ports:
      - 3000:3000
    working_dir: /app-frontend
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3000"]
      timeout: 10s
      retries: 5
  
